export enum QUERY_KEYS{
  GET_POST_BY_ID = 'GET_POST_BY_ID',
  GET_POST_REPLIES_BY_ID = 'GET_POST_REPLIES_BY_ID',

  QUERY_POST_LIST = 'POST_LIST',
  SEARCH_POST_LIST = 'SEARCH_POST_LIST',
  GET_RECENT_POSTS = 'GET_RECENT_POSTS',

  GET_USER_POSTS = 'GET_USER_POSTS',
  GET_USER_PROFILE = 'GET_USER_PROFILE',
  GET_USER_LIKES = 'GET_USER_LIKES',
  GET_USER_MEDIA = 'GET_USER_MEDIA',
  GET_CURRENT_USER = 'GET_CURRENT_USER',
  GET_BOOKMARKS = 'GET_BOOKMARKS',
  GET_NOTIFICATIONS = 'GET_NOTIFICATIONS',
  GET_TOP_RATED_POSTS = 'GET_TOP_RATED_POSTS',
  GET_FOLLOWING_POSTS = 'GET_FOLLOWING_POSTS',
  GET_USER_FOLLOWERS = 'GET_USER_FOLLOWERS',
  GET_USER_FOLLOWING = 'GET_USER_FOLLOWING',
  GET_PEOPLE_LIST = 'GET_PEOPLE_LIST',

  SEARCH_TOP = 'SEARCH_TOP',
  SEARCH_LATEST = 'SEARCH_LATEST',
  SEARCH_PEOPLE = 'SEARCH_PEOPLE',
  SEARCH_MEDIA = 'SEARCH_MEDIA',
}