export enum QUERY_KEYS{
  GET_RECENT_POSTS = 'GET_RECENT_POSTS',
  GET_POST_BY_ID = 'GET_POST_BY_ID',
  GET_USER_POSTS = 'GET_USER_POSTS',
  GET_USER_PROFILE = 'GET_USER_PROFILE',
  GET_USER_LIKES = 'GET_USER_LIKES',
  GET_USER_MEDIA = 'GET_USER_MEDIA',

  SEARCH = 'SEARCH',
}